print("")
print("Hello World")
print("Continue")
print("Hello")
print("")
print("Hello")
print("")
print("Hello World")
print("Continue")
print("Hello")
print("")
print("Hello World")
print("Continue")
print("Hello")
print("")
print("Hello World")
print("Continue")
print("Hello")
print("")
print("Hello World")
print("Continue")
